# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3431912e9fd09894de023d4b4ab5e57debd66bde3dc10067c3a5d562de206ee6432e85ceecaca88d082e72c69257f359f62bf622f7e6063133594da965db83ca

test:
  secret_key_base: 379dd942cb4a01964ddb16e07ee28f2ddf2454818d360dae8aa8601af547963430e484dac28cd9f65a9f35afa8b5bf90da4e62a478dcb0d1246f01520114262a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
